# Default values for wordpress-mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: alex-helm



wordpress:
  tier: frontend
  name: wordpress
  deployment:
    image: wordpress:4.8-apache
    containerPort: 80
    volumeMounts:
      name: wordpress-persistent-storage
      mountPath: /var/www/html
    volumes:
      name: wordpress-persistent-storage
      pVC:
        name: wp-pv-claim
  service:
    port: 80
    type: LoadBalancer
  pvc:
    requests:
      storage: 10Gi
    storageClassName: hcloud-volumes
  
mysql:
  name: mysql
  tier: mysql
  deployment:
    image: mysql:5.6
    containerPort: 3306
    volumeMounts:
      name: mysql-persistent-storage
      mountPath: /var/lib/mysql
    volumes:
      name: mysql-persistent-storage
      pVC:
        name: mysql-pv-claim
  service:
    port: 3306
  pvc:
    requests:
      storage: 10Gi
    storageClassName: hcloud-volumes
  
ingress:
  metadata: 
    clusterissuer: letsencrypt
    name: wp-ingress
  spec: 
    rules:
      host: alex-wp2.kubelab.spainip.es
  tls:
    host: alex-wp2.kubelab.spainip.es
    secretName: tls-wp-ingress
password: MYSQL_ROOT_PASSWORD
service:
  type: ClusterIP
  port: 80
