apiVersion: v1
kind: Service
metadata:
  name: {{ include "alex-wp-chart.fullname" . }}
  namespace: {{ .Values.service.namespace }}
  labels:
    {{- include "alex-wp-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "alex-wp-chart.selectorLabels" . | nindent 4 }}
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: alex
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None