apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  wp-pv-claim
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress-mysql.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wordpress.pvc.requests.storage }}
  storageClassName: {{ .Values.wordpress.pvc.storageClassName }}