apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress-mysql.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.wordpress.service.port }}
  selector:
    {{- include "wordpress-mysql.selectorLabels" . | nindent 4 }}
    tier: {{ .Values.wordpress.tier }}
  type: {{ .Values.wordpress.service.type }}
